on: pull_request
permissions:
  pull-requests: write
jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Add PR comment with step link
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const runId = context.runId;
            const repo = context.repo;
            const stepUrl = `https://github.com/${repo.owner}/${repo.repo}/actions/runs/${runId}/jobs/`;
            const commentBody = `
              ### Workflow Step Link
              You can view the details of the specific step in the workflow run [here](${stepUrl}).
            `;
            await github.rest.issues.createComment({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: context.payload.pull_request.number,
              body: commentBody
            });


      - run: echo ${{ github }}
